# Generated by Django 3.0.5 on 2020-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200503_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='raw_keyword',
            field=models.TextField(default=''),
        ),
    ]
