# Generated by Django 3.0.5 on 2020-05-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_note_raw_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='raw_keyword',
        ),
    ]
